
#Settings involving only the Random Teleporting aspect ##########

wild:

  #The title of the main menu
  menu-title: "Random Teleport"

  #The color of the glass in the main menu
  menu-glass: BLACK_STAINED_GLASS_PANE

  #The maxim distance to teleport the player to (only working if you don't have ChunkyBorder installed), works like a border for all teleports
  maximum-distance: 15000

  #Cooldown in seconds between random teleports (if the player teleports too many times, the waiting time will increase automaticaly to reduce spam)
  cooldown: 10

  #The time in hours in which new players have free random teleporting (set to 0 or -1 to disable)
  beginner-time: 6

  #The 3 distances the players can select. You can not add more distances, edit the available ones.
  distances:
    short:
      name: "Coal"    #The name shown in the menu
      price: 100      #The price (needs Vault to work)
      distance: 1000  #The max distance to teleport the players
      icon: COAL      #The menu icon
      lore:           #The lore of the menu item
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    medium:
      name: "Iron"
      price: 100
      distance: 1000
      icon: IRON_INGOT
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    long:
      name: "Diamond"
      price: 100
      distance: 1000
      icon: DIAMOND
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"

  #The worlds in which the players can teleport randomly
  enabled-worlds:
    - "world"

##################################################################

structures:
  cooldown: 86400 #Cooldown between structures teleports
  menu-title: "Teleport to structures" #The menu item
  menu-item: SPAWNER #The icon in the main menu
  menu-item-name: "Teleport to structures" #The main menu item's name
  menu-item-lore: #The main menu item's lore
    - "Lore 1"
    - "Lore 2"
  options:
    1:
      type: MINESHAFT #Must be valid structure name, this will also be the name shown in the menu, but formatted
      price: 100 #The price to teleport
      icon: MINECART #The icon in the menu
      lore: #The lore of the item in the menu
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    2:
      type: STRONGHOLD
      price: 100
      icon: ENDER_EYE
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    3:
      type: VILLAGE
      price: 100
      icon: CHEST
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"

biomes:
  cooldown: 86400
  menu-title: "Teleport to biomes"
  menu-item: OAK_SAPLING
  menu-item-name: "Teleport to biomes"
  menu-item-lore:
    - "Lore 1"
    - "Lore 2"
  options:
    1:
      type: BAMBOO_JUNGLE
      price: 100
      icon: BAMBOO
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    2:
      type: DESERT
      price: 100
      icon: SAND
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    3:
      type: FOREST
      price: 100
      icon: SPRUCE_SAPLING
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"

#Attention! Depending on your platform, you need to use different formatting codes!
#For Paper users - use the new MiniMessage format, it is awesome: https://webui.adventure.kyori.net/
#For Spigot or other platforms - use the old color codes (&c, &f), or use HEX like this: #80C7FDHello!

messages:
  no-money: "<dark_gray>(</dark_gray><red>❌</red><dark_gray>)</dark_gray> <white>You don't have enough money"
  disabled-world: "<dark_gray>(</dark_gray><red>❌</red><dark_gray>)</dark_gray> <white>This command doesn't work in this world"
  cooldown: "<dark_gray>(</dark_gray><red>❌</red><dark_gray>)</dark_gray> <white>You need to wait %time% minutes"
  no-structures: "<dark_gray>(</dark_gray><red>❌</red><dark_gray>)</dark_gray> <white>No structures were found near you"
  no-biomes: "<dark_gray>(</dark_gray><red>❌</red><dark_gray>)</dark_gray> <white>No biomes were found near you"
  not-player: "<dark_gray>(</dark_gray><red>❌</red><dark_gray>)</dark_gray> <white>You need to be a player in order to use this command"
  teleported-to-biome:
    - " "
    - "You were teleported to the nearest %biome% for $%price%"
    - "Tip: If the biome isn't near you, it may be under you or above you"
    - " "
  teleported-to-structure:
    - " "
    - "You were teleported to the nearest %structure% for $%price%"
    - "Tip: If the structure isn't near you, it may be under you or above you"
    - " "
  searching:
    title: "Searching.."
    subtitle: "Hold tight!"
  teleported:
    title: "You've been teleported"
    subtitle: "X: %x%, Y: %y%, Z: %z%"
  no-access:
    title: "Oops!"
    subtitle: "You don't have access to this command"

#Some misc settings
other:
  sound: BLOCK_NOTE_BLOCK_PLING
  particle: DRAGON_BREATH
  blindness: true #Give blindness to players for a short amount of time on teleporting?
  enable-structures: true
  enable-biomes: true #Only works on Paper servers
  simple-mode: false #Simple mode is basically, just the /wild command that teleports everyone
  simple-mode-max-distance: 10000 #The max range of the /wild command