wild:
  menu-title: "Random Teleport"
  menu-glass: BLACK_STAINED_GLASS_PANE
  minimum-distance: 1000
  maximum-distance: 15000
  avoid-regions: true
  cooldown: 10
  beginner-time: 6
  distances:
    short:
      name: "Coal"
      price: 100
      distance: 1000
      icon: COAL
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    medium:
      name: "Iron"
      price: 100
      distance: 1000
      icon: IRON_INGOT
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    long:
      name: "Diamond"
      price: 100
      distance: 1000
      icon: DIAMOND
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
  enabled-worlds:
    - "world"

structures:
  cooldown: 86400
  menu-title: "Teleport to structures"
  menu-item: SPAWNER
  menu-item-name: "Teleport to structures"
  menu-item-lore:
    - "Lore 1"
    - "Lore 2"
  options:
    1:
      type: MINESHAFT
      price: 100
      icon: MINECART
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"


messages:
  no-money: "You don't have enough money"
  disabled-world: "This command doesn't work in this world"
  cooldown: "You need to wait %time% minutes"
  no-structures: "No structures were found near you"
  not-player: "You need to be a player in order to use this command"
  teleported-to-structure:
    - " "
    - "You were teleported to the nearest %structure% for $%price%"
    - "Tip: If the structure isn't near you, it may be under you or above you"
    - " "
  searching:
    title: "Searching.."
    subtitle: "Hold tight!"
  teleported:
    title: "You've been teleported"
    subtitle: "X: %x%, Y: %y%, Z: %z%"
  no-access:
    title: "Oops!"
    subtitle: "You don't have access to this command"

other:
  sound: BLOCK_NOTE_BLOCK_PLING
  particle: DRAGON_BREATH
  blindness: true