wild:
  simple-mode: false #You can choose from simple or menu - simple is just the /wild command that teleports you, and the menu is the whole plugin shabang
  simple-mode-max-distance: 10000
  menu-title: "Random Teleport"
  menu-glass: BLACK_STAINED_GLASS_PANE
  maximum-distance: 15000
  cooldown: 10
  beginner-time: 6
  distances:
    short:
      name: "Coal"
      price: 100
      distance: 1000
      icon: COAL
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    medium:
      name: "Iron"
      price: 100
      distance: 1000
      icon: IRON_INGOT
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    long:
      name: "Diamond"
      price: 100
      distance: 1000
      icon: DIAMOND
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
  enabled-worlds:
    - "world"

structures:
  cooldown: 86400
  menu-title: "Teleport to structures"
  menu-item: SPAWNER
  menu-item-name: "Teleport to structures"
  menu-item-lore:
    - "Lore 1"
    - "Lore 2"
  options:
    1:
      type: MINESHAFT
      price: 100
      icon: MINECART
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    2:
      type: STRONGHOLD
      price: 100
      icon: ENDER_EYE
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    3:
      type: VILLAGE
      price: 100
      icon: CHEST
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"

biomes:
  cooldown: 86400
  menu-title: "Teleport to biomes"
  menu-item: OAK_SAPLING
  menu-item-name: "Teleport to biomes"
  menu-item-lore:
    - "Lore 1"
    - "Lore 2"
  options:
    1:
      type: BAMBOO_JUNGLE
      price: 100
      icon: BAMBOO
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    2:
      type: DESERT
      price: 100
      icon: SAND
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"
    3:
      type: FOREST
      price: 100
      icon: SPRUCE_SAPLING
      lore:
        - "Teleport distance: 100 blocks"
        - "Price: 100"

messages:
  no-money: "<dark_gray>(</dark_gray><red>❌</red><dark_gray>)</dark_gray> <white>You don't have enough money"
  disabled-world: "<dark_gray>(</dark_gray><red>❌</red><dark_gray>)</dark_gray> <white>This command doesn't work in this world"
  cooldown: "<dark_gray>(</dark_gray><red>❌</red><dark_gray>)</dark_gray> <white>You need to wait %time% minutes"
  no-structures: "<dark_gray>(</dark_gray><red>❌</red><dark_gray>)</dark_gray> <white>No structures were found near you"
  no-biomes: "<dark_gray>(</dark_gray><red>❌</red><dark_gray>)</dark_gray> <white>No biomes were found near you"
  not-player: "<dark_gray>(</dark_gray><red>❌</red><dark_gray>)</dark_gray> <white>You need to be a player in order to use this command"
  teleported-to-biome:
    - " "
    - "You were teleported to the nearest %biome% for $%price%"
    - "Tip: If the biome isn't near you, it may be under you or above you"
    - " "
  teleported-to-structure:
    - " "
    - "You were teleported to the nearest %structure% for $%price%"
    - "Tip: If the structure isn't near you, it may be under you or above you"
    - " "
  searching:
    title: "Searching.."
    subtitle: "Hold tight!"
  teleported:
    title: "You've been teleported"
    subtitle: "X: %x%, Y: %y%, Z: %z%"
  no-access:
    title: "Oops!"
    subtitle: "You don't have access to this command"

other:
  sound: BLOCK_NOTE_BLOCK_PLING
  particle: DRAGON_BREATH
  blindness: true
  enable-structures: true
  enable-biomes: true