##########################################
#                                        #
#                HEADER                  #
#                                        #
##########################################

main: com.Moshu.SmartWild.Main
name: SmartWild
version: 24.07.2024
description: A better wild plugin
author: Moshu
website: mc.b-zone.ro
softdepend: [Vault, WorldGuard, ChunkyBorder, MiniMessage]
api-version: "1.21"
libraries:
  - "net.kyori:adventure-api:4.11.0"

commands:
  wild:
    permission: smartwild.use
    aliases:
      - rtp


permissions:
  smartwild.use:
    default: op
    description: Use the main command
  smartwild.admin:
    default: op
    description: Bypass the restrictions such as cooldowns