##########################################
#                                        #
#                HEADER                  #
#                                        #
##########################################

main: com.Moshu.SmartWild.Main
name: SmartWild
version: 2022-08-18T15:12:17+03:00
description: A better wild plugin
author: Moshu
website: mc.b-zone.ro
softdepend: [Vault, PlaceholderAPI, WorldGuard, ChunkyBorder]
api-version: "1.19"

commands:
  a:


permissions:
  b: